# Generated by Django 5.1.1 on 2026-02-07 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rumour',
            fields=[
                ('rumour_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='รหัสข่าวลือ')),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อข่าว')),
                ('source', models.CharField(max_length=255, verbose_name='แหล่งที่มา')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('credibility_score', models.IntegerField(default=0, verbose_name='คะแนนความน่าเชื่อถือ')),
                ('status', models.CharField(choices=[('normal', 'ปกติ'), ('panic', 'Panic'), ('verified_true', 'ยืนยันว่าจริง'), ('verified_false', 'ยืนยันว่าเท็จ')], default='normal', max_length=20, verbose_name='สถานะ')),
            ],
            options={
                'verbose_name': 'ข่าวลือ',
                'verbose_name_plural': 'ข่าวลือ',
                'ordering': ['-credibility_score'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='รหัสผู้ใช้')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('role', models.CharField(choices=[('general_user', 'ผู้ใช้ทั่วไป'), ('verifier', 'ผู้ตรวจสอบ')], default='general_user', max_length=20, verbose_name='บทบาท')),
            ],
            options={
                'verbose_name': 'ผู้ใช้งาน',
                'verbose_name_plural': 'ผู้ใช้งาน',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='วันที่รายงาน')),
                ('report_type', models.CharField(choices=[('distorted', 'บิดเบือน'), ('inciting', 'ปลุกปั่น'), ('false', 'ข้อมูลเท็จ')], max_length=20, verbose_name='ประเภทรายงาน')),
                ('rumour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumors.rumour', verbose_name='ข่าวลือ')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumors.user', verbose_name='ผู้รายงาน')),
            ],
            options={
                'verbose_name': 'รายงาน',
                'verbose_name_plural': 'รายงาน',
                'unique_together': {('reporter', 'rumour')},
            },
        ),
    ]
